[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_SUPABASE_URL,SUPABASE_SERVICE_ROLE_KEY,SUPABASE_FUNCTION_URL"
  SECRETS_SCAN_OMIT_PATHS = "app/api/bookings/route.ts,app/api/test-supabase/route.ts"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/services/virtual-staging"
  to = "/services/virtual-services"
  status = 301